version: '3.8'

services:
  engine-cpu:
    container_name: engine-cpu-pposyab
    build:
      context: ${PWD}/BeautyGAN
      dockerfile: Dockerfile
    hostname: engine-cpu-pposyab
    tty: true
    stdin_open: true
    ports:
      - '58080:8080'
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #       - driver: nvidia
    #         count: all
    #         # device_ids: ['0']
    #         capabilities: [gpu]
    shm_size: 2g
    volumes:
      - ${PWD}/BeautyGAN/:/workspace
    environment:
      - TZ=Asia/Seoul
      - DISPLAY=localhost:0.0
  
  webapp:
    container_name: django-pposyab
    build:
      context: ${PWD}/WebApp
      dockerfile: Dockerfile
    hostname: django-pposyab
    tty: true
    stdin_open: true
    ports:
      - '8000:8000'
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #       - driver: nvidia
    #         count: all
    #         # device_ids: ['0']
    #         capabilities: [gpu]
    shm_size: 1g
    volumes:
      - ${PWD}/WebApp:/workspace
    environment:
      - TZ=Asia/Seoul
