version: '3.8'

services:
  beautygan:
    container_name: pposyab-engine-cpu
    build:
      context: ${PWD}/BeautyGAN
      dockerfile: Dockerfile
    hostname: pposyab-engine-cpu
    tty: true
    stdin_open: true
    networks:
      - pposyab
    expose:
      - 8000:8000
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #       - driver: nvidia
    #         count: all
    #         # device_ids: ['0']
    #         capabilities: [gpu]
    # shm_size: 2g
    volumes:
      - ${PWD}/BeautyGAN/:/workspace
    environment:
      - TZ=Asia/Seoul
      - DISPLAY=localhost:0.0
  
  webapp:
    container_name: pposyab-django
    build:
      context: ${PWD}/WebApp
      dockerfile: Dockerfile
    hostname: pposyab-django
    tty: true
    stdin_open: true
    networks:
      - pposyab
    ports:
      - 8000:8000
    depends_on:
      - beautygan
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #       - driver: nvidia
    #         count: all
    #         # device_ids: ['0']
    #         capabilities: [gpu]
    # shm_size: 1g
    volumes:
      - ${PWD}/WebApp:/workspace
    environment:
      - TZ=Asia/Seoul
    command: gunicorn WebApp.wsgi:application --bind 0.0.0.0:8000

networks:
  pposyab:
    driver: bridge